- hosts: localhost
  tasks:
  - debug:
      msg: "System has uuid {{ ansible_product_uuid }}"

  - name: Iterate over worker node
    debug: var=item
    with_items: "{{ test_worker_nodes_with_labels | from_yaml }}"

  - name: Test worker nodes | get iptables rules
    shell: /sbin/iptables -L OS_FIREWALL_ALLOW -n --line-numbers
    register: iptablesrules
    sudo: true
    with_items: "{{ test_worker_nodes_with_labels }}"

  - name: Test worker nodes | set iptables rules
    command: /sbin/iptables -A OS_FIREWALL_ALLOW -p tcp --dport 9000 -j ACCEPT -m comment --comment "test-svr"
    sudo: true
    when:
    - iptablesrules.stdout.find("test-svr") == -1
    with_items: "{{ test_worker_nodes_with_labels }}"

  - name: save iptables
    command: iptables-save
    sudo: true
